<?php

namespace SoftUniBlogBundle\Repository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $id
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function relatedActors(int $id)
    {
        return  $this
            ->createQueryBuilder('a')
            ->innerJoin('a.quotes','aq')
           // ->where('aq.id = :id')
            //->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
//SELECT a.title FROM actors a inner join actors_quotes aq on aq.actor_id=a.id where aq.quote_id=2
