<?php


namespace SoftUniBlogBundle\Repository;
/**
 * QuoteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getListWithCategories(){
//        $query = $this->getEntityManager()->createQuery(
//            'SELECT p,c
//                 FROM AppBundle:Product p
//                 JOIN p.category c
//                 '
//        );
//
//        return $query->getResult();
//    }
    public function getListWithVerses(){
        $query = $this->getEntityManager()->createQuery(
            'SELECT p,c 
                 FROM SoftUniBlogBundle:Actor p
                 JOIN p.category c
                 '
        );

        return $query->getResult();
    }

    public function relatedActors(int $id)
    {
        return  $this
            ->createQueryBuilder('q')
            ->innerJoin('q.actors','qa')
             ->where('q.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
